In [64]:
import pandas as pd

In [65]:
df=pd.read_csv('/content/new_data.csv',sep=',',error_bad_lines=False,names=['Address','Browser Info','Company','Credit Card','CC Exp Date','CC Security Code','Email','Job','IP Address','Language','Purchase Price'])
df.head()

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

,,,Address,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,Email,Job,IP Address,Language,Purchase Price
Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
16629 Pace Camp Apt. 448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Alexisborough,"NE 77130-7478""",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6.01E+15,20-Feb,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el
9374 Jasmine Spurs Suite 508,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
South John,"TN 84355-4179""",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3.34E+15,18-Nov,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr

In [66]:
df.to_csv("/content/new_data.csv")

In [72]:
df=pd.read_csv("/content/new_data.csv",header=1)
df.head()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,16629 Pace Camp Apt. 448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alexisborough,"NE 77130-7478""",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6.01E+15,20-Feb,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el
2,9374 Jasmine Spurs Suite 508,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,South John,"TN 84355-4179""",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3.34E+15,18-Nov,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr
4,Unit 0065 Box 5052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           20000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  object
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  object
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  object
 8   CC Provider       10000 non-null  object
 9   Email             10000 non-null  object
 10  Job               10000 non-null  object
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  object
 13  Purchase Price    10000 non-null  object
dtypes: object(14)
memory usage: 2.1+ MB